/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Preset = IDL.Record({
  'engineLevel1' : IDL.Nat,
  'engineLevel2' : IDL.Nat,
  'engineLevel3' : IDL.Nat,
  'engineLevel4' : IDL.Nat,
  'name' : IDL.Text,
  'virtualSimulation' : IDL.Bool,
  'volumeBooster' : IDL.Nat,
  'equalizerBands' : IDL.Vec(IDL.Int),
  'loudMode' : IDL.Bool,
  'bassBooster' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createPreset' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Int),
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'deletePreset' : IDL.Func([IDL.Text], [], []),
  'getActivePreset' : IDL.Func([], [IDL.Opt(Preset)], ['query']),
  'getAllPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
  'readPreset' : IDL.Func([IDL.Text], [Preset], ['query']),
  'setActivePreset' : IDL.Func([IDL.Text], [], []),
  'updatePreset' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Int),
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Preset = IDL.Record({
    'engineLevel1' : IDL.Nat,
    'engineLevel2' : IDL.Nat,
    'engineLevel3' : IDL.Nat,
    'engineLevel4' : IDL.Nat,
    'name' : IDL.Text,
    'virtualSimulation' : IDL.Bool,
    'volumeBooster' : IDL.Nat,
    'equalizerBands' : IDL.Vec(IDL.Int),
    'loudMode' : IDL.Bool,
    'bassBooster' : IDL.Nat,
  });
  
  return IDL.Service({
    'createPreset' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Int),
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'deletePreset' : IDL.Func([IDL.Text], [], []),
    'getActivePreset' : IDL.Func([], [IDL.Opt(Preset)], ['query']),
    'getAllPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
    'readPreset' : IDL.Func([IDL.Text], [Preset], ['query']),
    'setActivePreset' : IDL.Func([IDL.Text], [], []),
    'updatePreset' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Int),
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };