/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Preset {
  'engineLevel1' : bigint,
  'engineLevel2' : bigint,
  'engineLevel3' : bigint,
  'engineLevel4' : bigint,
  'name' : string,
  'virtualSimulation' : boolean,
  'volumeBooster' : bigint,
  'equalizerBands' : Array<bigint>,
  'loudMode' : boolean,
  'bassBooster' : bigint,
}
export interface _SERVICE {
  'createPreset' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      Array<bigint>,
      bigint,
      bigint,
      boolean,
      boolean,
    ],
    undefined
  >,
  'deletePreset' : ActorMethod<[string], undefined>,
  'getActivePreset' : ActorMethod<[], [] | [Preset]>,
  'getAllPresets' : ActorMethod<[], Array<Preset>>,
  'readPreset' : ActorMethod<[string], Preset>,
  'setActivePreset' : ActorMethod<[string], undefined>,
  'updatePreset' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      Array<bigint>,
      bigint,
      bigint,
      boolean,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];